import Foundation

// MARK: - 内置处理器

/// 尊重敏感内容标记。密码管理器复制的密码**不入库**。
///
/// 不做这条，本 App 就是个明文密码记录器。
/// 竞品 Paste 实测尊重四个 concealed UTI + 硬编码密码管理器 bundle 黑名单，此处照抄并扩充。
public struct ConcealedFilter: IngestProcessor {
    public let identifier = "core.concealed"

    /// macOS 上表示"这段内容不该被记录"的约定 UTI
    public static let concealedUTIs: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    /// 密码管理器 —— 即使没打 concealed 标记也不记录
    public static let blockedBundleIDs: Set<String> = [
        "com.agilebits.onepassword7", "com.1password.1password",
        "com.bitwarden.desktop",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
        "com.apple.keychainaccess",
        "in.sinew.Enpass-Desktop",
        "com.keepassium.mac", "org.keepassxc.keepassxc",
    ]

    public init() {}

    public func process(_ snapshot: inout RawSnapshot, context: inout IngestContext) -> IngestDecision {
        for r in snapshot.representations where Self.concealedUTIs.contains(r.uti) {
            return .drop(reason: "concealed:\(r.uti)")
        }
        if let bid = snapshot.sourceBundleID, Self.blockedBundleIDs.contains(bid) {
            return .drop(reason: "blocked-app:\(bid)")
        }
        return .accept
    }
}

/// 敏感内容识别 —— 命中则标 sensitive（加密 + 不入索引 + 短 TTL）。
///
/// 保守策略：宁可漏判为普通，也不误判导致内容 60 秒后消失。
public struct SensitivityClassifier: IngestProcessor {
    public let identifier = "core.sensitivity"

    public init() {}

    private static let patterns: [(String, NSRegularExpression?)] = {
        let raw = [
            ("jwt",        #"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b"#),
            ("aws-key",    #"\bAKIA[0-9A-Z]{16}\b"#),
            ("private-key", #"-----BEGIN [A-Z ]*PRIVATE KEY-----"#),
            ("bearer",     #"(?i)\b(bearer|authorization)\s*[:=]\s*\S{20,}"#),
            ("pwd-assign", #"(?i)\b(password|passwd|pwd|secret|api[_-]?key|access[_-]?token)\s*[:=]\s*\S{6,}"#),
            ("conn-str",   #"(?i)\b(jdbc|mongodb|redis|postgres|mysql)://\S*:\S+@\S+"#),
        ]
        return raw.map { ($0.0, try? NSRegularExpression(pattern: $0.1)) }
    }()

    public func process(_ snapshot: inout RawSnapshot, context: inout IngestContext) -> IngestDecision {
        let text = context.preview
        guard !text.isEmpty, text.count < 20_000 else { return .accept }
        let range = NSRange(text.startIndex..., in: text)
        for (name, re) in Self.patterns {
            if let re, re.firstMatch(in: text, range: range) != nil {
                context.sensitivity = .sensitive
                context.notes.append("sensitive:\(name)")
                return .accept
            }
        }
        return .accept
    }
}

/// 类型识别 + 生成预览文本。
public struct TypeClassifier: IngestProcessor {
    public let identifier = "core.classify"

    public init() {}

    public func process(_ snapshot: inout RawSnapshot, context: inout IngestContext) -> IngestDecision {
        let utis = Set(snapshot.representations.map(\.uti))

        // 文件引用优先判定 —— 剪贴板天生只给路径（实测 200MB 视频 = 76 字节）
        if utis.contains("public.file-url") {
            context.kind = .fileRef
            context.preview = Self.text(from: snapshot, uti: "public.file-url")
                .removingPercentEncoding ?? ""
            return .accept
        }
        if utis.contains(where: { $0.hasPrefix("public.") && ($0.contains("image") || $0 == "public.png" || $0 == "public.tiff" || $0 == "public.jpeg" || $0 == "public.heic") }) {
            context.kind = .image
            let bytes = snapshot.representations.reduce(0) { $0 + $1.data.count }
            let size = ByteCountFormatter().string(fromByteCount: Int64(bytes))
            // 读像素尺寸只解析元数据头、不解码像素，代价可忽略，但对用户有用得多
            let dims = snapshot.representations
                .compactMap { ThumbnailStore.pixelSize(of: $0.data) }
                .first
            context.preview = dims.map { "图片 \($0.width)×\($0.height) · \(size)" } ?? "图片 · \(size)"
            return .accept
        }

        let plain = Self.text(from: snapshot, uti: "public.utf8-plain-text")
        context.preview = plain

        // ⚠️ JSON 判定必须排在 richText **前面**。
        // 从网页或日志里选中一段 JSON 复制，剪贴板上同时有 html/rtf，
        // 先判 richText 的话这条就被标成"富文本"了 —— 用户看到的是「格式」而不是「JSON」。
        if JSONDetector.looksLikeJSON(plain) {
            context.kind = .json
        } else if SQLDetector.looksLikeSQL(plain) {
            // 同理排在 richText 之前：从 Navicat / 网页里复制 SQL 也会带 html/rtf
            context.kind = .sql
        } else if ShellDetector.looksLikeShell(plain) {
            // 同理：从文档/终端复制命令也常带 html
            context.kind = .shell
        } else if utis.contains("public.rtf") || utis.contains("public.html") {
            context.kind = .richText
        } else if plain.hasPrefix("http://") || plain.hasPrefix("https://") {
            context.kind = .url
        } else if Self.looksLikeCode(plain) {
            context.kind = .code
        } else if !plain.isEmpty {
            context.kind = .text
        }
        return .accept
    }

    static func text(from snapshot: RawSnapshot, uti: String) -> String {
        guard let d = snapshot.representations.first(where: { $0.uti == uti })?.data else { return "" }
        return String(data: d, encoding: .utf8) ?? ""
    }

    static func looksLikeCode(_ s: String) -> Bool {
        guard s.count > 20 else { return false }
        let markers = ["{", "}", "();", "=>", "func ", "def ", "public ", "private ",
                       "select ", "SELECT ", "import ", "class ", "<?xml", "#!/"]
        let hits = markers.reduce(0) { $0 + (s.contains($1) ? 1 : 0) }
        return hits >= 2
    }
}

/// 体积闸门 —— 超限降级只留元数据，不让单条撑爆库
public struct SizeGuard: IngestProcessor {
    public let identifier = "core.sizeguard"
    public let maxBytes: Int

    public init(maxBytes: Int = 50 * 1024 * 1024) {
        self.maxBytes = maxBytes
    }

    public func process(_ snapshot: inout RawSnapshot, context: inout IngestContext) -> IngestDecision {
        let total = snapshot.representations.reduce(0) { $0 + $1.data.count }
        if total > maxBytes {
            return .drop(reason: "oversize:\(total)")
        }
        return .accept
    }
}

extension ProcessorRegistry {
    /// 默认管道。**顺序有意义**：先分类产出 preview，敏感识别才有文本可查。
    public static func defaultRegistry() -> ProcessorRegistry {
        let r = ProcessorRegistry()
        r.register(ConcealedFilter())
        r.register(SizeGuard())
        r.register(TypeClassifier())
        r.register(SensitivityClassifier())
        return r
    }
}
